kind: pipeline
type: docker
name: default

steps:
  - name: Install dependencies
    image: node:14
    commands:
      - cd front
      - npm install
  - name: Linting front
    image: node:14
    commands:
      - cd front
      - npm run lint
  - name: Building front
    image: node:14
    commands:
      - cd front
      - npm run build
  - name: Packaging
    image: luky/rsync
    commands:
      - mkdir .ci_dist
      - rsync -vr --exclude back.iml --exclude .gitignore  back/  .ci_dist/
      - rsync -vr front/dist/ .ci_dist/public/

  - name: Build result
    image: iankoulski/tree
    commands:
      - tree -a .ci_dist

  - name: publish
    image: plugins/github-release
    settings:
      files: .ci_dist/*
      title: Tomcat manager
      draft: true
      prerelease: true
      api_key:
        from_secret: release_key
    when:
      event:
        - tag

